# Generated by Django 6.0.3 on 2026-03-28 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('final_evaluation_comments', models.TextField(blank=True)),
                ('final_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('report_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('academic_supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'academic_sup'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_placements', to=settings.AUTH_USER_MODEL)),
                ('organizations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='organizations.organization')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='accounts.studentprofile')),
                ('workplace_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_placements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('tasks_performed', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='SUBMITTED', max_length=20)),
                ('challenges', models.TextField(blank=True)),
                ('attendance_days', models.PositiveIntegerField(default=5)),
                ('supervisor_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('workplace_feedback', models.TextField(blank=True, null=True)),
                ('academic_feedback', models.TextField(blank=True, null=True)),
                ('is_verified_by_workplace', models.BooleanField(default=False)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='placements.internshipplacement')),
            ],
        ),
    ]
