# Generated by Django 6.0.3 on 2026-03-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipplacement',
            old_name='organization',
            new_name='organizations',
        ),
    ]
