# Generated by Django 6.0.3 on 2026-03-25 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_alter_user_email_and_more'),
        ('placements', '0002_rename_organization_internshipplacement_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipplacement',
            name='organizations',
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='accounts.organization'),
        ),
    ]
