# Generated by Django 6.0.3 on 2026-03-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_alter_internshipplacement_academic_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='SUBMITTED', max_length=20),
        ),
    ]
