# Generated by Django 6.0.3 on 2026-03-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_weeklylog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipplacement',
            name='final_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='report_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
