# Generated by Django 6.0.3 on 2026-03-25 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_internshipplacement_final_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='academic_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='is_verified_by_workplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='workplace_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='workplace_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_placements', to=settings.AUTH_USER_MODEL),
        ),
    ]
